trigger:
  branches:
    include:
    - master
    - develop
    - feature/netcore
  paths:
    exclude:
    - README.md
    - CHANGELOG.md
    - CONTRIBUTING.md

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  major: 5
  minor: 1
  # creates a counter called versioncounter and seeds it at 100 and then assigns the value to a variable named buildNo.
  buildNo: $[counter('geomversioncounter', 100)]
  
name: $(BuildDefinitionName)_$(SourceBranchName)_$(major).$(minor).$(buildNo)

jobs:
- job: XbimGeometryBuild
  timeoutInMinutes: 120
  steps:
  # Windows script setting up  $(packageversion) of the nuget package based on branch
  # Master branch
  - script: |
      echo ##vso[task.setvariable variable=packageversion]$(major).$(minor).$(buildNo)
    displayName: 'Setting Nuget PackageVersion'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  # Any other branch
  - script: |
      echo ##vso[task.setvariable variable=packageversion]$(major).$(minor).$(buildNo)-$(Build.SourceBranchName)
    displayName: 'Setting Prerelease Nuget PackageVersion'
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  
  
  # Windows script setting up $(fileversion) used to stamp AssemblyFileVersions. 
  # By convention we use 'Major.Minor.BuildNo.0' on Master and 'Major.Minor.0.BuildNo' on other branches
  # Master branch
  - script: | 
      echo ##vso[task.setvariable variable=fileversion]$(major).$(minor).$(buildNo).0
    displayName: 'Setting FileVersion'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  # Any other branch
  - script: | 
      echo ##vso[task.setvariable variable=fileversion]$(major).$(minor).0.$(buildNo)
    displayName: 'Setting Prerelease FileVersion'
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  
  #Task group has not been exported, task groups are not supported yet
  
  - task: NuGetToolInstaller@0
    displayName: 'Use a new NuGet'
    inputs:
      versionSpec: '5.6.0'

  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'
    inputs:
      packageFeedSelector: 'nugetOrg'
      versionSelector: 'latestPreRelease'
  
  # Version .NET Core project files
  # Description - Applies a version to a .NET Core assembly via the .csproj files based on the build number. 
  # Based on https://github.com/rfennell/AzurePipelines/wiki/Version-Assemblies-and-Packages-Tasks-YAML#versiondotnetcoreassembliestask
  - task: VersionDotNetCoreAssemblies@2
    displayName: 'Update netcore FileVersions'
    inputs: 
      # Required arguments
      Path: $(Build.SourcesDirectory)
      VersionNumber: $(fileversion)
      VersionRegex: \d+\.\d+\.\d+\.\d+
      FilenamePattern: .csproj
      Field: fileversion
      OutputVersion: OutputedVersion
  - task: VersionDotNetCoreAssemblies@2
    displayName: 'Update global Versions'
    inputs: 
      # Required arguments
      Path: $(Build.SourcesDirectory)
      VersionNumber: $(packageversion)
      VersionRegex: \d+\.\d+\.\d+.*
      FilenamePattern: directory.build.props
      Field: Version
      OutputVersion: OutputedVersion
  
  # Version Native C++
  - powershell: |
      ((Get-Content -path Xbim.Geometry.Engine\app.rc -Raw) -replace '"FileVersion", "5.1.0.0"','"FileVersion", "$(fileversion)"') | Set-Content -Path Xbim.Geometry.Engine\app.rc
    displayName: 'Update Native C++ FileVersion'
  - powershell: |
      ((Get-Content -path Xbim.Geometry.Engine\app.rc -Raw) -replace 'FILEVERSION 5,1,0,0','FILEVERSION $(major),$(minor),$(buildNo),0') | Set-Content -Path Xbim.Geometry.Engine\app.rc
    displayName: 'Update Native C++ FILEVERSION - for Master'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  - powershell: |
      ((Get-Content -path Xbim.Geometry.Engine\app.rc -Raw) -replace 'FILEVERSION 5,1,0,0','FILEVERSION $(major),$(minor),0,$(buildNo)') | Set-Content -Path Xbim.Geometry.Engine\app.rc
    displayName: 'Update Native C++ FILEVERSION - for Pre-Release'
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  
  - task: NuGetCommand@2
    displayName: 'NuGet restore Xbim.Geometry.Engine.sln'
    inputs:
      restoreSolution: 'Xbim.Geometry.Engine.sln'
      feedsToUse: config
      nugetConfigPath: nuget.config
  
  - task: DeleteFiles@1
    displayName: 'Delete old *.nupkg files from $(build.sourcesdirectory)'
    inputs:
      SourceFolder: '$(build.sourcesdirectory)'
      Contents: '**\bin\$(BuildConfiguration)\**\*.nupkg'

  - task: VSBuild@1
    displayName: 'Build and pack solution Xbim.Geometry.Engine.sln'
    inputs:
      solution: 'Xbim.Geometry.Engine.sln'
      vsVersion: '16.0' # vs2019
      msbuildArgs: '/t:build'
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'

  # Xbim.Geometry meta package
  - powershell: |
      ((Get-Content -path Xbim.Geometry\Xbim.Geometry.tmpl -Raw) -replace '{{version}}','$(packageversion)') | Set-Content -Path Xbim.Geometry\Xbim.Geometry.nuspec
    name: Geometry_metapackage_Update
  - script: nuget pack Xbim.Geometry\Xbim.Geometry.nuspec -OutputDirectory Xbim.Geometry/bin/$(BuildConfiguration)
    name: Geometry_metapackage_Pack
  
  # Disabled until we fix the build server environment
  # - task: VSTest@2
  #   displayName: 'VsTest - testAssemblies'
  #   inputs:
  #     testSelector: 'testAssemblies'
  #     testAssemblyVer2: '**\bin\$(BuildConfiguration)\**\Xbim.Geometry.Engine.Interop.Tests.dll'
  #     searchFolder: '$(System.DefaultWorkingDirectory)'
  #     runSettingsFile: 'test.runsettings'
  #     vsTestVersion: 'toolsInstaller'
  #     codeCoverageEnabled: false
  #     platform: '$(BuildPlatform)'
  #     configuration: '$(BuildConfiguration)'
  
  - task: PublishSymbols@1
    displayName: 'Publish symbols path: '
    inputs:
      SearchPattern: '**\bin\**\*.pdb'
    enabled: false
    continueOnError: true
  
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(build.sourcesdirectory)'
      Contents: '**\bin\$(BuildConfiguration)\*.nupkg'
      TargetFolder: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
  
  # Publish to master or develop MyGet feed based on the source branch
  - task: NuGetCommand@2
    name: 'MyGetPublishing_Master'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: 'MyGetMaster'
      versioningScheme: byEnvVar
      versionEnvVar: packageversion
  
  - task: NuGetCommand@2
    name: 'MyGetPublishing_Develop'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    inputs:
      command: push
      nuGetFeedType: external
      publishFeedCredentials: 'MyGetDev'
      versioningScheme: byEnvVar
      versionEnvVar: packageversion
  - task: NuGetCommand@2
    name: 'MyGetPublishing_FlexGet'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/feature/netcore'))
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '2591d379-784d-4b57-88f5-a932c93cbffd'
